apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: shtp_traffic
    user: shtp_admin
    secureJsonData:
      password: ShtpSecure2026!
    jsonData:
      sslmode: disable
      postgresVersion: 15
      timescaledb: false
    isDefault: true
